# Generated by Django 3.0.3 on 2020-06-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0002_lignefacture_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignefacture',
            name='prix',
        ),
    ]
