# Generated by Django 3.0.4 on 2020-07-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0003_lignecommande_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecommande',
            name='panier',
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=1)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_pan', to='Bill.Panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_pan', to='Bill.Produit')),
            ],
        ),
    ]
