# Generated by Django 3.0.3 on 2020-06-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0003_remove_lignefacture_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
