# Generated by Django 3.0.4 on 2020-07-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0004_auto_20200704_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
