# Generated by Django 3.0.3 on 2020-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0004_auto_20200613_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='prix',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='lignefacture',
            name='prix',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
