# Generated by Django 3.0.3 on 2020-06-13 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0006_auto_20200613_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacture',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Bill.Produit'),
        ),
    ]
