# Generated by Django 3.0.4 on 2020-07-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0006_auto_20200708_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL),
        ),
    ]
